### PR TITLE
feat: http support

### PR DESCRIPTION
**Pull request by ranpro**

### CODE REVIEW

**Comment by ranpro** [comment]
This may sound humorous, but in certain regions, it is necessary to use a proxy in order to access OpenAI. The proxy used may not necessarily be utilizing the HTTPS protocol.

**Comment by debuggerone** [comment]
I don't see any humor in using techniques that work against the rules of openai. There are restrictions on available locations for reasons.

**Comment by nunomaduro** [comment]
It's missing tests.

**Comment by ranpro** [comment]
> It's missing tests.

sorry, i just completed the unit tests, thank you.

**Pull request merged**
